name: test a las 20 horas UTC horas

on:
  schedule:
    - cron: "0 18 * * *"
    - cron: "0 17 * * *"
    - cron: "55 16 * * *"

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
             echo "Hola"

      - name: list
        run: |
             ls -lhtrsa

      - name: curl
        run: |
             curl www.google.es

